# Generated by Django 3.2.4 on 2021-07-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210704_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('address2', models.CharField(max_length=1000)),
                ('Country', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField(max_length=6)),
                ('phone', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
